name: Build Windows Installer

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Tools
      run: |
        choco install ninja -y
        choco install nsis -y

    - name: Install Qt (MSVC 2022)
      uses: jurplel/install-qt-action@v4
      with:
        version: 6.8.3
        host: windows
        target: desktop
        arch: win64_msvc2022_64
        modules: qtquick

    - name: Setup MSVC Environment
      shell: cmd
      run: |
        call "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvars64.bat" || ^
        call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"

    - name: Configure CMake
      shell: cmd
      run: |
        cmake -S . -B build -G "Ninja" -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=cl.exe -DCMAKE_CXX_COMPILER=cl.exe

    - name: Build Application
      shell: cmd
      run: |
        cmake --build build --config Release

    - name: Deploy Qt Dependencies
      shell: cmd
      run: |
        windeployqt --release --qmldir=. build\apptest_qt.exe

    - name: Copy MSVC Runtime (Auto detect)
      shell: pwsh
      run: |
        $redist = (Get-ChildItem "C:\Program Files\Microsoft Visual Studio\2022" -Recurse -Directory -Filter "Microsoft.VC.*.CRT" | Where-Object { $_.FullName -like "*x64*" } | Select-Object -First 1).FullName
        Copy-Item "$redist\*.dll" build\ -Force

    - name: Build Installer
      shell: cmd
      run: |
        "C:\Program Files (x86)\NSIS\makensis.exe" installer.nsi

    - name: Upload Installer Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Windows-Installer
        path: apptest_qt-Installer-*.exe

