name: Build Qt App (Windows)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    env:
      BUILD_DIR: build
      INSTALL_DIR: install
      QT_VERSION: 6.8.3
      QT_ARCH: win64_msvc2022_64

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          choco install ninja -y
          choco install nsis -y

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{ env.QT_VERSION }}
          host: windows
          target: desktop
          arch: ${{ env.QT_ARCH }}
          cache: true

      - name: Setup MSVC Environment
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Configure CMake (MSVC)
        run: cmake -B ${{ env.BUILD_DIR }} -G "Visual Studio 17 2022" -A x64 -S .

      - name: Build (Release)
        run: cmake --build ${{ env.BUILD_DIR }} --config Release

      - name: Prepare Install Dir
        run: |
          mkdir ${{ env.INSTALL_DIR }}
          mkdir ${{ env.INSTALL_DIR }}\bin
          copy ${{ env.BUILD_DIR }}\Release\apptest_qt.exe ${{ env.INSTALL_DIR }}\bin\

      - name: Deploy Qt
        run: windeployqt ${{ env.INSTALL_DIR }}\bin\apptest_qt.exe --qmldir .

      - name: Build Installer
        run: '"C:\Program Files (x86)\NSIS\makensis.exe" installer.nsi'

      - name: Upload Installer
        uses: actions/upload-artifact@v4
        with:
          name: Windows-Installer
          path: "*.exe"

