name: Build Qt App (Windows)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    env:
      BUILD_DIR: build
      INSTALL_DIR: install
      QT_VERSION: 6.8
      QT_MODULES: qtmultimedia
      APP_NAME: apptest_qt

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Tools
        run: |
          choco install ninja -y
          choco install nsis -y

      - name: Setup Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{ env.QT_VERSION }}
          host: windows
          target: desktop
          arch: win64_msvc2022_64
          modules: ${{ env.QT_MODULES }}
          cache: true

      - name: Setup MSVC Compiler
        uses: microsoft/setup-msbuild@v1

      - name: Configure CMake
        run: cmake -B ${{ env.BUILD_DIR }} -G "Visual Studio 17 2022" -S . -A x64 -DCMAKE_INSTALL_PREFIX="${{ env.INSTALL_DIR }}" -DCMAKE_BUILD_TYPE=Release

      - name: Build App
        run: cmake --build ${{ env.BUILD_DIR }} --config Release

      - name: Install App
        run: cmake --install ${{ env.BUILD_DIR }} --config Release

      - name: Find windeployqt path
        id: windeployqt
        shell: pwsh
        run: |
          $wqt = Get-ChildItem -Path "C:\Users\runneradmin\Qt" -Recurse -Filter windeployqt.exe | Select-Object -First 1
          if (-not $wqt) { throw "windeployqt not found!" }
          echo "WQT_PATH=$($wqt.FullName)" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Bundle Qt Dependencies
        shell: pwsh
        run: |
          & "${env:WQT_PATH}" "${{ env.INSTALL_DIR }}\bin\${{ env.APP_NAME }}.exe" --release --compiler-runtime

      - name: Build Installer (NSIS)
        shell: pwsh
        run: |
          & "C:\Program Files (x86)\NSIS\makensis.exe" /V2 installer.nsi

      - name: Upload Installer
        uses: actions/upload-artifact@v4
        with:
          name: Windows-Installer
          path: "*.exe"

