name: Build Windows Installer

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Clean old build cache (if exists)
  shell: cmd
  run: |
    IF EXIST build (
      rmdir /S /Q build
    )


    - name: Install Tools
      run: |
        choco install ninja -y
        choco install nsis -y

    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: 6.8.3
        host: windows
        target: desktop
        arch: win64_msvc2022_64

    - name: Configure CMake (MSVC)
      run: cmake -S . -B build -G "Ninja" -DCMAKE_BUILD_TYPE=Release

    - name: Build App (MSVC)
      run: cmake --build build --config Release

    - name: Deploy Qt Dependencies
      run: |
        set PATH=%Qt6_DIR%/bin;%PATH%
        windeployqt --release --qmldir=. "build\Desktop_Qt_6_8_3-Release\apptest_qt.exe"

    - name: Copy MSVC Runtime
      run: |
        xcopy "C:\Program Files\Microsoft Visual Studio\2022\*\VC\Redist\MSVC\*\x64\*.dll" "build\Desktop_Qt_6_8_3-Release" /Y

    - name: Build Installer
      run: |
        "C:\Program Files (x86)\NSIS\makensis.exe" installer\installer.nsi

    - name: Upload Installer
      uses: actions/upload-artifact@v4
      with:
        name: Windows-Installer
        path: apptest_qt-Installer-*.exe

