name: Build Windows Installer

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Tools
      run: |
        choco install ninja -y
        choco install nsis -y

    - name: Install Qt (MSVC)
      uses: jurplel/install-qt-action@v4
      with:
        version: 6.8.3
        host: windows
        target: desktop
        arch: win64_msvc2022_64
        modules: qtquick qtmlanguageclient

    - name: Setup MSVC Environment
      shell: cmd
      run: call "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvars64.bat"

    - name: Configure CMake (force MSVC)
      shell: cmd
      run: |
        cmake -S . -B build -G "Ninja" ^
          -DCMAKE_BUILD_TYPE=Release ^
          -DCMAKE_C_COMPILER=cl.exe ^
          -DCMAKE_CXX_COMPILER=cl.exe

    - name: Build App
      shell: cmd
      run: cmake --build build --config Release

    - name: Deploy Qt Dependencies
      shell: cmd
      run: windeployqt --release --qmldir=. build\apptest_qt.exe

    - name: Copy MSVC Runtime
      shell: cmd
      run: |
        xcopy "%VCToolsRedistDir%x64\Microsoft.VC*.CRT\*.dll" build\ /Y

    - name: Build Installer
      shell: cmd
      run: "C:\Program Files (x86)\NSIS\makensis.exe" installer.nsi

    - name: Upload Installer
      uses: actions/upload-artifact@v4
      with:
        name: Windows-Installer
        path: apptest_qt-Installer-*.exe

