name: Build Qt QML Application (Windows)

on:
  push:
    branches:
      - main # or your main development branch
  pull_request:
    branches:
      - main # or your main development branch

jobs:
  build-windows:
    runs-on: windows-latest # Use a Windows runner

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4 # Action to checkout your code

    - name: Install Qt
      uses: jurplel/install-qt-action@v3 # Action to install Qt
      with:
        version: '5.15.2' # Specify your desired Qt version
        target: 'desktop'
        arch: 'win64_msvc2019_64' # Or your target architecture/compiler

    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release

    - name: Build application
      run: |
        cd build
        cmake --build . --config Release

    - name: Deploy Qt dependencies
      run: |
        # Use windeployqt to collect necessary Qt DLLs and plugins
        # Adjust paths as needed for your specific project and build output
        cd build/Release # Or wherever your executable is built
        "C:\Qt\5.15.2\msvc2019_64\bin\windeployqt.exe" --qmldir ../../qml --no-translations your_app_name.exe

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: qt-qml-app-windows
        path: build/Release # Path to your built application and dependencies
