name: Build Qt App (Windows)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    env:
      BUILD_DIR: build
      INSTALL_DIR: install
      QT_VERSION: 6.8
      QT_MODULES: qtmultimedia

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install tools
        run: |
          choco install ninja -y
          choco install nsis -y

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{ env.QT_VERSION }}
          host: windows
          target: desktop
          arch: win64_msvc2022_64
          modules: ${{ env.QT_MODULES }}
          cache: true

      - name: Set up MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Configure CMake
        run: cmake -B ${{ env.BUILD_DIR }} -G "Ninja" -S . -DCMAKE_INSTALL_PREFIX="${{ env.INSTALL_DIR }}" -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build ${{ env.BUILD_DIR }} --config Release

      - name: Install
        run: cmake --install ${{ env.BUILD_DIR }} --config Release

      # ✅ Auto-detect the built .exe
      - name: Detect application executable
        id: find_exe
        shell: pwsh
        run: |
          $exe = Get-ChildItem "${{ env.INSTALL_DIR }}\bin" -Filter *.exe | Select-Object -First 1
          if (-not $exe) { Write-Error "No .exe found in install/bin" }
          echo "exe_path=${exe.FullName}" >> $env:GITHUB_OUTPUT
          echo "Detected application: $($exe.Name)"

      # ✅ Deploy Qt + MSVC runtime
      - name: Bundle Qt Dependencies
        shell: pwsh
        env:
          EXE: ${{ steps.find_exe.outputs.exe_path }}
        run: |
          & "$Env:Qt6_DIR\bin\windeployqt.exe" "$Env:EXE" --release --compiler-runtime


      - name: Build Installer (NSIS)
        shell: pwsh
        run: |
          & "C:\Program Files (x86)\NSIS\makensis.exe" /V2 installer.nsi

      - name: Upload Installer Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Windows-Installer
          path: "*.exe"

