name: Build Windows Installer

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: 6.8.3
        host: windows
        target: desktop
        arch: win64_msvc2019_64

    - name: Install NSIS
      run: choco install nsis -y

    - name: Configure (CMake)
      run: cmake -S . -B build -G "Ninja" -DCMAKE_BUILD_TYPE=Release

    - name: Build (Release)
      run: cmake --build build --config Release

    - name: Deploy Qt Dependencies
      run: |
        set PATH=%PATH%;%Qt6_DIR%/bin
        windeployqt --release build\apptest_qt.exe

    - name: Create Installer
      run: |
        "C:\Program Files (x86)\NSIS\makensis.exe" installer\installer.nsi

    - name: Upload Installer Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Windows-Installer
        path: apptest_qt-Installer-*.exe

