name: Build Qt App (Windows)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    env:
      BUILD_DIR: build
      INSTALL_DIR: install
      QT_VERSION: 6.8.3
      QT_ARCH: win64_msvc2022_64

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          choco install ninja -y
          choco install nsis -y

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{ env.QT_VERSION }}
          host: windows
          target: desktop
          arch: ${{ env.QT_ARCH }}
          cache: true

      - name: Configure CMake
        run: cmake -B ${{ env.BUILD_DIR }} -G "Ninja" -S . -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build ${{ env.BUILD_DIR }} --config Release

      # ✅ Make install folder manually
      - name: Prepare install directory
        run: |
          mkdir ${{ env.INSTALL_DIR }}
          mkdir ${{ env.INSTALL_DIR }}\bin
          copy ${{ env.BUILD_DIR }}\apptest_qt.exe ${{ env.INSTALL_DIR }}\bin\

      # ✅ Deploy Qt DLLs directly to install/bin
      - name: Bundle Qt runtime
        run: windeployqt ${{ env.INSTALL_DIR }}\bin\apptest_qt.exe --qmldir .

      - name: Build installer (.exe)
        run: '"C:\Program Files (x86)\NSIS\makensis.exe" installer.nsi'

      - name: Upload Installer
        uses: actions/upload-artifact@v4
        with:
          name: Windows-Installer
          path: "*.exe"

