name: Build Windows Installer

on:
  push:
  pull_request:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.8.3'   # ✅ match your Linux version
        host: windows
        target: desktop
        arch: win64_msvc2022_64

    - name: Configure project
      run: cmake -S . -B build -G "NMake Makefiles"

    - name: Build project
      run: cmake --build build --config Release

    - name: Install NSIS
      run: choco install nsis -y

    - name: Deploy Qt DLLs (windeployqt)
      run: |
        mkdir install
        mkdir install\bin
        copy build\Release\apptest_qt.exe install\bin\
        windeployqt install\bin\apptest_qt.exe --qmldir .

    - name: Create Installer
      run: makensis installer.nsi

    - name: Upload Installer
      uses: actions/upload-artifact@v3
      with:
        name: Windows-Installer
        path: *.exe

